# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 1.6
  - nightly

codecov: true
coveralls: true

notifications:
  email: false

jobs:
  # Uncomment the following lines to allow failures on nightly julia
  # (tests will run but not make your overall status red)
  allow_failures:
    - julia: nightly
  fast_finish: true

  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
