name = "ModernRoboticsBook"
uuid = "5e1d693a-52d4-54aa-90a0-6f94c7384aed"
authors = ["Henrique Ferrolho <henriqueferrolho@gmail.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1.10"
