name = "ModernRoboticsBook"
uuid = "5e1d693a-52d4-54aa-90a0-6f94c7384aed"
authors = ["Henrique Ferrolho <henriqueferrolho@gmail.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
